### ISSUE TITLE
irrelevant

### ISSUE THREAD

**Issue by logrusx** [SuperTux88/gentoo-overlay#10]
NVM, I was too quick to file an issue.

**Comment by SuperTux88** [comment]
I renamed it anyway ... and also fixed the URLs for zenmonitor3, as the old repo didn't exist anymore, so you wouldn't have been able to install it anyway. But everything should hopefully work now.

Back when I created the ebuild for zenpower(3), I still kept the old name, because the kernel module was still named `zenpower` (without the 3), but since others started to use an ebuild name with a 3 (as how the repo is named), it's probably a good idea to rename it was you suggested, so it's named the same in all overlays.

**Comment by logrusx** [comment]
> as the old repo didn't exist anymore

That's why I realized it was irrelevant as the project seemed dead and if somebody used it, it would already have been brought up.

Thanks for the rename anyway.

**Comment by SuperTux88** [comment]
> That's why I realized it was irrelevant as the project seemed dead

Yeah, the project _is_ kinda dead, as it isn't updated anymore, but it still works (at least for old CPUs, no idea if new CPUs work as well, as new CPUs where the reason why it was forked from without a number to the name with the 3, and maybe it would need another change for even newer CPUs).

And since I still had it installed before the repo was moved to a new place, I didn't notice the url-change, as it doesn't get re-downloaded if I never need to reinstall it. And at least nobody else was trying to install it from my overlay and reported the broken url.
