### ISSUE TITLE
gui-apps/wluma build fail

### ISSUE THREAD

**Issue by salacio** [SuperTux88/gentoo-overlay#4]
I was trying to build gui-apps/wluma and it fails during the build phase. I'm a little new to this, so it could be I have something configured wrong.

It was asking for libclang.so originally, so I installed sys-devel/clang in case that was the issue, but now it's having another issue.

emerge --info gui-apps/wluma - https://bpa.st/JLN24
first try before sys-devel/clang - https://bpa.st/PRC2U
after sys-devel/clang - https://bpa.st/VOBYQ

**Comment by SuperTux88** [comment]
OK, I thought that clang is a dependency of rust, but it looks like that's not always the case (but was on all of my systems, but maybe because of something else). But I'll add `sys-devel/clang` as a dependency, so that should fix the first problem.

The weird thing is now, I also can't build it anymore because I now also have the second error. I last built it successfully 3 weeks ago, but now it doesn't build anymore and I have no idea why yet. I didn't change anything on the ebuild, but I guess something else on my system must have changed, which now breaks the build.

**Comment by SuperTux88** [comment]
OK, I found the issue, there is a dependency of wluma (v4l-sys, visible in your logs) which isn't compatible with clang 16 (see https://github.com/rust-lang/rust-bindgen/issues/2312). Limiting the build to use clang/llvm <16 worked for me, so I hope it also works for you now.

I also created an upstream PR to update the dependency to be compatible with clang 16, so that should fix the problem with future versions of wluma: https://github.com/maximbaz/wluma/pull/75

**Comment by salacio** [comment]
Yea that got it to build. There was an issue, however the default configuration was set it was looking for the iio sensor and iio-sensor-proxy won't install by default without systemd apparently, but I just copied and edited the one from upstream for now, and I'll figure out the rest later. Thanks.
