### ISSUE TITLE
x11-drivers/evdi-1.14.5::supertux88 fails to build with lto

### ISSUE THREAD

**Issue by Arniiiii** [SuperTux88/gentoo-overlay#8]
How to reproduce:
get a gcc , enable lto , get ERROR missing MODULE_LICENSE()
[build.log.txt](https://github.com/user-attachments/files/16202768/build.log.txt)

/etc/portage/*
[portage.zip](https://github.com/user-attachments/files/16202770/portage.zip)

profile : default/linux/amd64/23.0/split-usr/desktop/plasma

**Comment by SuperTux88** [comment]
Are you sure this is a problem with the ebuild? I can't find anything I would need to do differently and it sounds more like it could be a bug in the upstream code? :thinking: Are you able to build this with lto manually without the ebuild? Otherwise you can maybe create a bugreport in [the upstream repo](https://github.com/DisplayLink/evdi), because I currently have no idea what I would need to change in the ebuild to fix this error, as I don't do anything special to build the module. Or since you seem to have some experience with lto, do you know any other kernel-module ebuilds and know what they do differently for lto to work?

**Comment by Arniiiii** [comment]
I've downloaded their release tarball, tried to compile with lto via :

`CFLAGS="-O3 -pipe -march=alderlake -mabm -mno-cldemote -mno-kl -mno-pconfig -mno-sgx -mno-widekl -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=48 --param=l2-cache-size=30720 -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -fgraphite-identity -floop-interchange -floop-strip-mine -floop-nest-optimize -ggdb3 -frecord-gcc-switches" CXXFLAGS="-O3 -pipe -march=alderlake -mabm -mno-cldemote -mno-kl -mno-pconfig -mno-sgx -mno-widekl -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=48 --param=l2-cache-size=30720 -flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -fgraphite-identity -floop-interchange -floop-strip-mine -floop-nest-optimize -ggdb3 -frecord-gcc-switches" make all`

and it seems to compile= successfully all their stuff, if I read their Makefile correctly


Honestly idk what's with the ebuild, but without lto it works

**Comment by Arniiiii** [comment]
> do you know any other kernel-module ebuilds and know what they do differently for lto to work?

I remember droidcam , but haven't checked their [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-video/droidcam/droidcam-2.1.3.ebuild)

**Comment by SuperTux88** [comment]
If you just call `make all` like that, it doesn't actually compile the module at all, so no surprise it doesn't fail, as it doesn't run anything that could trigger the error. You also need to set `CONFIG_DRM_EVDI=m` (this seems to be a bug with the latest version, they removed it from the Makefile, but without it, it doesn't build the module, so I put it back in the ebuild).

But as a minimal example, this also fails when building it directly: `CFLAGS="-flto" CXXFLAGS="-flto" CONFIG_DRM_EVDI=m make all`

So it looks like the module just doesn't build with lto at the moment. I added `filter-lto` to the ebuild, which removes the lto flag again (if present), so it builds without lto regardless of the flag. This doesn't really help you if you want to build it with lto enabled, because now it just enforces lto to be disabled. But I can't do anything to make lto work, but at least the ebuild doesn't fail anymore if you have lto enabled.

If you want it to work with lto, you can create a bug-report upstream, and once the minimal command from above doesn't fail anymore, I can remove the `filter-lto` again.
